name: Docker Build and Push

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag kyamo/fbcallrouter:$GITHUB_RELEASE_TAG
        docker tag kyamo/fbcallrouter:$GITHUB_RELEASE_TAG kyamo/fbcallrouter:latest
        docker push kyamo/fbcallrouter
      env:
        GITHUB_RELEASE_TAG: ${{ github.event.release.tag_name }}

